services:
  - type: web
    name: ai-velocity-dashboard
    runtime: docker
    plan: free
    autoDeploy: true
    repo: https://github.com/Prathima-create/ai-velocity-portal
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "3000"
      - key: RENDER
        value: "true"
